import React from 'react'

export const metadata = {
  title: 'Search - JewelOne',
  description: 'Generated by create next app',
}

const Search = () => {
  return (
    <div>
      Search
    </div>
  )
}

export default Search
