import React from 'react'


export const metadata = {
  title: 'Our Story - Jewelone',
  description: 'Generated by create next app',
}

const OurStory = () => {
  return (
    <div>
      OurStory
    </div>
  )
}

export default OurStory
