import React from 'react'
 
export const metadata = {
  title: 'Collections - JewelOne',
  description: 'Generated by create next app',
}

const Collections = () => {
  return (
    <div>
      Collections
    </div>
  )
}

export default Collections
