import React from 'react'

export const metadata = {
  title: 'What We Have - JewelOne',
  description: 'Generated by create next app',
}

const WhatWeHave = () => {
  return (
    <div>
      WhatWeHave
    </div>
  )
}

export default WhatWeHave
