import React from 'react'

export const metadata = {
    title: 'Sale - Jewelone',
    description: 'Generated by create next app',
  }
  

const Sale = () => {
  return (
    <div>
      Sale
    </div>
  )
}

export default Sale
