import './globals.css'
import { Inter } from 'next/font/google'
import "bootstrap/dist/css/bootstrap.min.css";
import NavBar from '@/components/NavBar/NavBar';
import AnnouncementBar from '@/components/AnnouncementBar/AnnouncementBar';
import Footer from '@/components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Jewelone - Next JS APP',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AnnouncementBar/>
        <NavBar/>
        <main>
        {children}
        </main>
        <Footer/>
        </body>
    </html>
  )
}
