import React from 'react'

export const metadata = {
  title: 'Wedding Celebrations - Jewelone',
  description: 'Generated by create next app',
}

const WeddingCelebrations = () => {
  return (
    <div>
      WeddingCelebrations
    </div>
  )
}

export default WeddingCelebrations
